#' Run the CoeditorAI RStudio Addin on the currently selected text
#'
#' @param original_text A character. Edited text. If a text is not provided,
#' the current text selection from the active file in RStudio IDE
#' is used by default.
#'
#' @param debug A logical. The `TRUE` function returns a shiny app object
#' of class `shiny.appobj` for debugging and testing purposes
#' without actually running the app.
#' By default, this option is set to `FALSE`.
#'
#' @returns A character string.
#' The last output text generated by the CoeditorAI Add-in session.
#'
#' @export
#'
#' @examples
#' if (interactive()) {
#'   "Select text in RStudio IDE or pass it as a character string" |>
#'   coedit_text()
#' }
#'
#' if (interactive()) {
#'   coedit_text()
#' }

coedit_text <- function(original_text = get_selection(),
                        debug         = FALSE) {

  check_user_credentials()

  if (length(original_text) == 0 || original_text == "") {

    original_text <- paste0("**No text selected!** Open a document, ",
                            "select a text that you want to edit, ",
                            "and click **Restart** button in CoeditorAI.")
  }

  if (!is_selected_text_valid(original_text)) return(invisible(NULL))

  shiny::addResourcePath("www", system.file("www", package = "CoeditorAI"))

  bootswatch        <- "simplex"
  tooltip_max_width <- "300px"
  bs_version        <- 5
  preset            <- "bootstrap"

  light <- bslib::bs_theme(preset            = bootswatch,
                           version           = bs_version,
                           tooltip_max_width = tooltip_max_width,
                           "navbar-expand-breakpoint" =  "sm")

  dark  <- bslib::bs_theme(preset            = bootswatch,
                           version           = bs_version,
                           tooltip_max_width = tooltip_max_width,
                           bg                = "#002B36",
                           fg                = "white",
                           "navbar-expand-breakpoint" =  "sm")

  ui <- bslib::page_navbar(
    id           = "panels",
    window_title = "CoeditorAI",
    underline    = TRUE,
    inverse      = FALSE,
    title        = shiny::img(id     = "hex_logo",
                              src    = "www/logo.png",
                              width  = "50px",
                              heigth = "50px",
                              align  = "center"),
    selected     = NULL,
    padding      = c("0px", "10px", "200px", "10px"),
    collapsible  = TRUE,
    position     = c("fixed-bottom"),
    theme        = {
      if (getOption("coeditorai.dark_mode", FALSE)) dark else light
    },

    header = mod_header_buttons_ui("header_buttons"),

    bslib::nav_panel(
      title = "CoeditorAI",
      icon  = shiny::icon("user-pen"),

      shiny::tags$head(
        shiny::tags$link(rel  = "shortcut icon",
                         type = "image/x-icon",
                         href = "www/favicon.ico"),
        shiny::tags$link(rel  = "stylesheet",
                         type = "text/css",
                         href = "www/style.css"),
       shiny::tags$style(shiny::HTML(
         ".bslib-card, .tab-content, .tab-pane, .card-body {
              overflow: visible !important;
         }"))
      ),
      shinyjs::useShinyjs(),
      shiny::includeScript(system.file("www/script.js",
                                       package = "CoeditorAI")),
      shinybusy::add_busy_bar(
        timeout  = 1000,
        color    = "#D7220F",
        height   = "10px",
        centered = FALSE),

      insert_top_space("text_editors"),
      shiny::tags$div(id = "text_editors"),
      insert_bottom_space("text_editors")
    ),

    bslib::nav_panel(
    title = "Settings",
    icon  = shiny::icon("gear"),

      insert_top_space("settings"),
      mod_settings_ui("settings"),
      insert_bottom_space("settings")
    ),

    bslib::nav_spacer(),

    bslib::nav_panel(
      title = "About",
      icon  = shiny::icon("circle-info"),

      insert_top_space("about"),
      mod_about_ui("about"),
      insert_bottom_space("about")
    ),

    bslib::nav_panel(
      title = "Q&A",
      icon  = shiny::icon("circle-question", class = "fa-solid"),

      insert_top_space("qanda"),
      mod_qanda_ui("quanda"),
      insert_bottom_space("qanda")
    ),

    bslib::nav_panel(
      title = "Account",
      icon  = shiny::icon("user-gear"),

      insert_top_space("account"),
      mod_account_ui("account"),
      insert_bottom_space("account")
    )
  )

  server <- function(input, output, session) {

    shinyjs::onclick("hex_logo",
                     bslib::nav_select("panels",
                                       selected = "CoeditorAI"))

    session_id       <- shiny::reactiveVal(rlang::hash(original_text))
    last_output_text <- shiny::reactiveVal(original_text)
    editors_counter  <- shiny::reactiveVal(1)
    editors_outputs  <- shiny::reactiveValues()
    editors_drops    <- shiny::reactiveValues()

    shiny::exportTestValues(
      session_id       = { session_id() },
      last_output_text = { last_output_text() },
      editors_counter  = { editors_counter() },
      editors_outputs  = {
        shiny::reactiveValuesToList(editors_outputs) |>
          Map(f = function(x) x())
      }
    )

    header_buttons <-
      shiny::callModule(module           = mod_header_buttons_server,
                        id               = "header_buttons",
                        session_id       = session_id,
                        last_output_text = last_output_text,
                        editors_counter  = editors_counter)
    settings <-
      shiny::callModule(module = mod_settings_server,
                        id     = "settings")
    about <-
      shiny::callModule(module = mod_about_server,
                        id     = "about")
    account <-
      shiny::callModule(module = mod_account_server,
                        id     = "account")

    shiny::observe(session$setCurrentTheme(
      if (isTRUE(settings$dark_mode())) dark else light
    ))

    shiny::observeEvent(editors_counter(), {

      last_output <- shiny::isolate(last_output_text())
      editor_id   <- paste0("text_editor_", editors_counter())

      shiny::insertUI(
        selector = "#text_editors",
        where    = "beforeEnd",
        ui       = mod_text_coeditor_ui(editor_id))

      editor_outputs <-
        mod_text_coeditor_server(
          id          = editor_id,
          module_id   = editor_id,
          temperature = settings$temperature,
          style       = settings$style,
          session_id  = session_id,
          input_text  = last_output)

      editors_outputs[[editor_id]] <- editor_outputs$output_text
      editors_drops[[editor_id]]   <- editor_outputs$drop_editor

      shiny::observeEvent(editors_outputs[[editor_id]](), {

        editor_output <- editors_outputs[[editor_id]]()
        if (!is.character(editor_output)) return()

        editors_counter(editors_counter() + 1)
        last_output_text(editor_output)
      })

      shiny::observeEvent(editors_drops[[editor_id]](), {
        shiny::removeUI(selector = paste0("#", editor_id))
      })

      shinyjs::runjs(
        paste0('document.getElementById("', editor_id, '").scrollIntoView();')
      ) |> shinyjs::delay(ms = 500)
    })

  }

  shiny_app <- shiny::shinyApp(ui     = ui,
                               server = server)

  if (debug) return(shiny_app)

  viewer <- shiny::paneViewer(minHeight = 550)

  shiny::runGadget(app    = shiny_app,
                   viewer = viewer)
}
